import { useState, useEffect, useRef } from "react";
import { 
  BookOpen, 
  HelpCircle, 
  Calendar, 
  Award, 
  Clock, 
  Sparkles, 
  RefreshCw, 
  LogOut, 
  GraduationCap, 
  Database,
  Home,
  Bookmark
} from "lucide-react";
import { CourseModule, ProblemSolution, Deadline, UserProfile, ResourceLink } from "./types";

// Import modular page views
import Landing from "./views/Landing";
import Dashboard from "./views/Dashboard";
import Courses from "./views/Courses";
import Problems from "./views/Problems";
import SignLanguage from "./views/SignLanguage";
import ResourceLibrary from "./views/ResourceLibrary";

// Import Firebase Auth & Firestore Client Services
import { db, auth, OperationType, handleFirestoreError } from "./firebase";
import { 
  onAuthStateChanged, 
  signOut 
} from "firebase/auth";
import { 
  doc, 
  getDoc, 
  setDoc, 
  updateDoc, 
  collection, 
  query, 
  where, 
  orderBy, 
  limit, 
  getDocs, 
  deleteDoc, 
  onSnapshot 
} from "firebase/firestore";

// Academic presets shared across application views safely
const COURSE_PRESETS = [
  { subject: "Computer Science", topic: "Recursion & Trees", level: "Beginner", icon: "💻" },
  { subject: "Calculus", topic: "Limits & Integrals", level: "Intermediate", icon: "📐" },
  { subject: "Physics", topic: "Gravitational Tension Forces", level: "Advanced", icon: "🚀" },
  { subject: "Quantum Physics", topic: "Schrödinger Wave Mechanics", level: "Advanced", icon: "⚛️" },
  { subject: "Machine Learning", topic: "Neural Backpropagation", level: "Advanced", icon: "🧠" },
  { subject: "Distributed Systems", topic: "Paxos Consensus Engine", level: "Advanced", icon: "🌐" },
  { subject: "Calculus", topic: "Stokes' & Green's Theorems", level: "Advanced", icon: "🧮" }
];

const PROBLEM_PRESETS = [
  { subject: "Computer Science", statement: "Implement binary search tree node insertion without creating standard stack overflow errors during recursion." },
  { subject: "Calculus", statement: "Find the volume of the solid generated by revolving the region bounded by y = sqrt(x) and y = x^2 about the x-axis." },
  { subject: "Physics", statement: "A 5kg block is pulled on a flat surface with a mechanical dynamic coefficient of friction of 0.35. Compute the tension force needed to achieve steady velocity." },
  { subject: "Quantum Physics", statement: "Identify the eigenstates and calculate the transition probability of a hydrogen atom electron stimulated by a coherent electromagnetic pulse at resonant frequency." },
  { subject: "Machine Learning", statement: "Formulate the matrix weight update rule using the chain rule for a layer transition containing cross-entropy loss, Softmax layers, and L2 regularization." },
  { subject: "Distributed Systems", statement: "Design a quorum state sequence under Paxos where multiple cluster partition boundaries cause a split-brain consensus failure, and demonstrate resolution." }
];

export default function App() {
  // ----------------------------------------------------
  // Authentication & Session States
  // ----------------------------------------------------
  const [isLoggedIn, setIsLoggedIn] = useState<boolean>(() => {
    return localStorage.getItem("study_path_logged_in") === "true";
  });
  const [currentUser, setCurrentUser] = useState<{ email: string; name: string } | null>(() => {
    const saved = localStorage.getItem("study_path_current_user");
    if (saved) {
      try { return JSON.parse(saved); } catch (_) {}
    }
    return null;
  });

  // Local student profile metrics container (backing offline achievements)
  const [profile, setProfile] = useState<UserProfile>(() => {
    const saved = localStorage.getItem("student_companion_profile_v2");
    if (saved) {
      try { return JSON.parse(saved); } catch (_) {}
    }
    return {
      xp: 150,
      studyMinutes: 45,
      completedMilestones: [],
      solvedProblemsCount: 2,
      deadlines: [],
      quizScores: {}
    };
  });

  // ----------------------------------------------------
  // Full-Stack Server-Synced Database Arrays
  // ----------------------------------------------------
  const [serverStateStatus, setServerStateStatus] = useState<'idle' | 'syncing' | 'synced' | 'error'>('idle');
  const [serverDeadlines, setServerDeadlines] = useState<Deadline[]>([]);
  const [serverStudyLogs, setServerStudyLogs] = useState<any[]>([]);
  const [serverLeaderboard, setServerLeaderboard] = useState<any[]>([]);
  const [serverScratchNotes, setServerScratchNotes] = useState<string>("");
  const [scratchNotesInput, setScratchNotesInput] = useState<string>("");
  const [serverResources, setServerResources] = useState<ResourceLink[]>([]);
  const [notesSaving, setNotesSaving] = useState(false);
  const [leaderboardSubmitting, setLeaderboardSubmitting] = useState(false);
  const [dbResetting, setDbResetting] = useState(false);

  // Active navigation tab router
  const [activeTab, setActiveTab] = useState<'dashboard' | 'courses' | 'problems' | 'signlang' | 'resources'>('dashboard');

  // Input states for generating study modules
  const [targetSubject, setTargetSubject] = useState("Computer Science");
  const [targetTopic, setTargetTopic] = useState("Recursion & Trees");
  const [targetLevel, setTargetLevel] = useState("Intermediate");
  const [generatingCourse, setGeneratingCourse] = useState(false);
  const [generatedCourse, setGeneratedCourse] = useState<CourseModule | null>(null);

  // Input states for explaining problems
  const [problemSubject, setProblemSubject] = useState("Computer Science");
  const [problemText, setProblemText] = useState("");
  const [explainingProblem, setExplainingProblem] = useState(false);
  const [explainedProblem, setExplainedProblem] = useState<ProblemSolution | null>(null);

  // Diagnostic state guides for problem solver steps
  const [currentProblemStep, setCurrentProblemStep] = useState(0);
  const [stepQuizAnswer, setStepQuizAnswer] = useState<number | null>(null);
  const [quizChecked, setQuizChecked] = useState(false);
  const [quizSuccess, setQuizSuccess] = useState<boolean | null>(null);

  // Real Countdowns Study stopwatch Pomodoros
  const [timerIsRunning, setTimerIsRunning] = useState(false);
  const [timerSecondsLeft, setTimerSecondsLeft] = useState(1500); // 25 minutes default Pomodoro
  const [timerInitial, setTimerInitial] = useState(1500);
  const timerIntervalRef = useRef<NodeJS.Timeout | null>(null);

  // Course Quiz Check State
  const [courseQuizAnswers, setCourseQuizAnswers] = useState<Record<number, number>>({});
  const [courseQuizChecked, setCourseQuizChecked] = useState(false);
  const [courseQuizScore, setCourseQuizScore] = useState<number | null>(null);

  // New Deadline quick form controllers
  const [newDlTitle, setNewDlTitle] = useState("");
  const [newDlSubject, setNewDlSubject] = useState("Computer Science");
  const [newDlDate, setNewDlDate] = useState("");

  // System toast alerts
  const [toast, setToast] = useState<{ message: string; type: "success" | "info" } | null>(null);

  const showToast = (message: string, type: "success" | "info" = "success") => {
    setToast({ message, type });
    setTimeout(() => setToast(null), 4000);
  };

  // Query simulated offline server state as fallback
  const fetchServerState = async (silent = false) => {
    if (!silent) setServerStateStatus('syncing');
    try {
      const res = await fetch("/api/state");
      if (!res.ok) throw new Error("Sync failed");
      const data = await res.json();
      setServerDeadlines(data.deadlines || []);
      setServerStudyLogs(data.studyLogs || []);
      setServerLeaderboard(data.leaderboard || []);
      setServerScratchNotes(data.scratchNotes || "");
      setServerResources(data.resources || []);
      if (scratchNotesInput === "" || !silent) {
        setScratchNotesInput(data.scratchNotes || "");
      }
      setServerStateStatus('synced');
    } catch (err) {
      console.warn("Failed to query full-stack companion state:", err);
      if (!silent) setServerStateStatus('error');
    }
  };

  // Helper updater that updates local profile AND secure Firestore asynchronously
  const handleProfileUpdate = (newProfileOrFn: UserProfile | ((prev: UserProfile) => UserProfile)) => {
    setProfile(prev => {
      const next = typeof newProfileOrFn === "function" ? newProfileOrFn(prev) : newProfileOrFn;
      
      // Save synchronously to local storage
      localStorage.setItem("student_companion_profile_v2", JSON.stringify(next));

      // Sync to Firestore if signed in
      const user = auth.currentUser;
      if (user) {
        const userDocRef = doc(db, "users", user.uid);
        updateDoc(userDocRef, {
          ...next,
          updatedAt: new Date().toISOString()
        } as any).catch((err) => {
          // Fallback with merge options
          setDoc(userDocRef, {
            ...next,
            updatedAt: new Date().toISOString()
          }, { merge: true }).catch((e) => {
            handleFirestoreError(e, OperationType.UPDATE, `users/${user.uid}`);
          });
        });
      }
      return next;
    });
  };

  // Process Mounts & Real-time Firebase Sync Orchestration
  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, async (firebaseUser) => {
      if (firebaseUser) {
        setIsLoggedIn(true);
        setCurrentUser({
          email: firebaseUser.email || "",
          name: firebaseUser.displayName || firebaseUser.email?.split("@")[0] || "Scholar"
        });
        setServerStateStatus('syncing');

        // Setup/retrieve User profile metadata doc
        const userDocRef = doc(db, "users", firebaseUser.uid);
        try {
          const userSnap = await getDoc(userDocRef);
          if (!userSnap.exists()) {
            const initialProfile: UserProfile = {
              name: firebaseUser.displayName || firebaseUser.email?.split("@")[0] || "Scholar",
              email: firebaseUser.email || "",
              xp: profile.xp,
              studyMinutes: profile.studyMinutes,
              completedMilestones: profile.completedMilestones,
              solvedProblemsCount: profile.solvedProblemsCount,
              deadlines: profile.deadlines || [],
              quizScores: profile.quizScores,
              createdAt: new Date().toISOString(),
              updatedAt: new Date().toISOString()
            };
            await setDoc(userDocRef, initialProfile);
            setProfile(initialProfile);
          } else {
            const serverProfile = userSnap.data() as UserProfile;
            setProfile(serverProfile);
          }
        } catch (e) {
          handleFirestoreError(e, OperationType.GET, `users/${firebaseUser.uid}`);
        }

        // Establish the 5 real-time cloud datastore observers
        
        // 1. Deadlines
        const unsubDeadlines = onSnapshot(
          query(collection(db, "deadlines"), where("userId", "==", firebaseUser.uid)),
          (snapshot) => {
            const list: Deadline[] = [];
            snapshot.forEach((snap) => {
              list.push({ id: snap.id, ...snap.data() } as any);
            });
            setServerDeadlines(list);
            setServerStateStatus('synced');
          },
          (error) => {
            handleFirestoreError(error, OperationType.LIST, "deadlines");
          }
        );

        // 2. Study Logs
        const unsubLogs = onSnapshot(
          query(collection(db, "studyLogs"), where("userId", "==", firebaseUser.uid)),
          (snapshot) => {
            const list: any[] = [];
            snapshot.forEach((snap) => {
              list.push({ id: snap.id, ...snap.data() });
            });
            setServerStudyLogs(list);
          },
          (error) => {
            handleFirestoreError(error, OperationType.LIST, "studyLogs");
          }
        );

        // 3. Research Workspace Drafts
        const unsubNotes = onSnapshot(
          doc(db, "scratchNotes", firebaseUser.uid),
          (snap) => {
            if (snap.exists()) {
              const content = snap.data().content || "";
              setServerScratchNotes(content);
              setScratchNotesInput((prev) => prev === "" ? content : prev);
            } else {
              setServerScratchNotes("");
            }
          },
          (error) => {
            handleFirestoreError(error, OperationType.GET, `scratchNotes/${firebaseUser.uid}`);
          }
        );

        // 4. Resource Bookmarks
        const unsubResources = onSnapshot(
          query(collection(db, "resources"), where("userId", "==", firebaseUser.uid)),
          (snapshot) => {
            const list: ResourceLink[] = [];
            snapshot.forEach((snap) => {
              list.push({ id: snap.id, ...snap.data() } as any);
            });
            setServerResources(list);
          },
          (error) => {
            handleFirestoreError(error, OperationType.LIST, "resources");
          }
        );

        // 5. Global Leaderboard (Live dynamic roster sorted by XP)
        const unsubLeaderboard = onSnapshot(
          query(collection(db, "users"), orderBy("xp", "desc"), limit(20)),
          (snapshot) => {
            const list: any[] = [];
            snapshot.forEach((snap) => {
              const data = snap.data();
              list.push({
                name: data.name || "Anonymous Scholar",
                xp: data.xp || 0,
                badge: Math.floor((data.xp || 0) / 100) >= 5 ? "Elite Scholar 🎓" : "Rising Star 🌟"
              });
            });
            setServerLeaderboard(list);
          },
          (error) => {
            handleFirestoreError(error, OperationType.LIST, "users");
          }
        );

        return () => {
          unsubDeadlines();
          unsubLogs();
          unsubNotes();
          unsubResources();
          unsubLeaderboard();
        };

      } else {
        setIsLoggedIn(false);
        setCurrentUser(null);
        fetchServerState(true);
      }
    });

    return () => unsubscribe();
  }, []);

  useEffect(() => {
    localStorage.setItem("student_companion_profile_v2", JSON.stringify(profile));
  }, [profile]);

  // Synchronizers — Firebase Direct CRUD Orchestrators
  const addResourceToServer = async (title: string, url: string, courseSubject: string, category: ResourceLink["category"], notes?: string) => {
    const user = auth.currentUser;
    if (!user) {
      showToast("Signed in offline. Please authenticate with your Google account to sync bookmark links.", "info");
      return;
    }
    try {
      const resId = "res-uid-" + Date.now();
      await setDoc(doc(db, "resources", resId), {
        userId: user.uid,
        title,
        url,
        courseSubject,
        category,
        notes: notes || "",
        isFavorite: false,
        createdAt: new Date().toISOString()
      });
      showToast("📚 Saved academic link to secure cloud database!", "success");
    } catch (e) {
      handleFirestoreError(e, OperationType.CREATE, "resources");
    }
  };

  const toggleResourceFavoriteOnServer = async (id: string) => {
    const user = auth.currentUser;
    if (!user) return;
    try {
      const resourceRef = doc(db, "resources", id);
      const snap = await getDoc(resourceRef);
      if (snap.exists() && snap.data().userId === user.uid) {
        await updateDoc(resourceRef, {
          isFavorite: !snap.data().isFavorite
        });
        showToast("💖 Updated favorite status in remote cloud database.", "success");
      }
    } catch (e) {
      handleFirestoreError(e, OperationType.UPDATE, `resources/${id}`);
    }
  };

  const deleteResourceFromServer = async (id: string) => {
    const user = auth.currentUser;
    if (!user) return;
    try {
      await deleteDoc(doc(db, "resources", id));
      showToast("🗑️ Completely removed resource link from cloud storage.", "success");
    } catch (e) {
      handleFirestoreError(e, OperationType.DELETE, `resources/${id}`);
    }
  };

  const submitDeadlineToServer = async (title: string, subject: string, date: string) => {
    const user = auth.currentUser;
    if (!user) return;
    try {
      const dlId = "dl-uid-" + Date.now();
      await setDoc(doc(db, "deadlines", dlId), {
        userId: user.uid,
        title,
        subject,
        date,
        completed: false,
        createdAt: new Date().toISOString()
      });
      showToast("📅 Saved academic deadline to cloud database!", "success");
    } catch (e) {
      handleFirestoreError(e, OperationType.CREATE, "deadlines");
    }
  };

  const toggleDeadlineOnServer = async (id: string) => {
    const user = auth.currentUser;
    if (!user) return;
    try {
      const dlRef = doc(db, "deadlines", id);
      const snap = await getDoc(dlRef);
      if (snap.exists() && snap.data().userId === user.uid) {
        await updateDoc(dlRef, {
          completed: !snap.data().completed
        });
        showToast("✓ Deadline progression synced with back-end database.", "success");
      }
    } catch (e) {
      handleFirestoreError(e, OperationType.UPDATE, `deadlines/${id}`);
    }
  };

  const deleteDeadlineFromServer = async (id: string) => {
    const user = auth.currentUser;
    if (!user) return;
    try {
      await deleteDoc(doc(db, "deadlines", id));
      showToast("🗑️ Deleted milestone deadline from server database.", "success");
    } catch (e) {
      handleFirestoreError(e, OperationType.DELETE, `deadlines/${id}`);
    }
  };

  const logStudySessionToServer = async (topic: string, mins: number, xpGained: number, comments: string) => {
    const user = auth.currentUser;
    if (!user) return;
    try {
      const logId = "log-uid-" + Date.now();
      await setDoc(doc(db, "studyLogs", logId), {
        userId: user.uid,
        topic,
        duration: mins,
        date: new Date().toISOString().split("T")[0],
        xpGained,
        comments: comments || "",
        createdAt: new Date().toISOString()
      });
    } catch (e) {
      handleFirestoreError(e, OperationType.CREATE, "studyLogs");
    }
  };

  const saveScratchNotesToServer = async () => {
    const user = auth.currentUser;
    if (!user) return;
    setNotesSaving(true);
    try {
      await setDoc(doc(db, "scratchNotes", user.uid), {
        userId: user.uid,
        content: scratchNotesInput,
        updatedAt: new Date().toISOString()
      });
      showToast("💾 Research Note drafts synced to back–end study database!", "success");
    } catch (e) {
      handleFirestoreError(e, OperationType.UPDATE, `scratchNotes/${user.uid}`);
    } finally {
      setNotesSaving(false);
    }
  };

  const submitLeaderboardScore = async (name: string, currentXp: number, currentBadge: string) => {
    const user = auth.currentUser;
    if (!user) return;
    setLeaderboardSubmitting(true);
    try {
      const userDocRef = doc(db, "users", user.uid);
      await updateDoc(userDocRef, {
        name: name,
        xp: currentXp,
        updatedAt: new Date().toISOString()
      });
    } catch (e) {
      handleFirestoreError(e, OperationType.UPDATE, `users/${user.uid}`);
    } finally {
      setLeaderboardSubmitting(false);
    }
  };

  const resetFullstackDatabaseInstance = async () => {
    const user = auth.currentUser;
    if (!user) return;
    setDbResetting(true);
    try {
      // 1. Reset profile metrics
      const userDocRef = doc(db, "users", user.uid);
      const initialProfile = {
        name: user.displayName || user.email?.split("@")[0] || "Scholar",
        email: user.email || "",
        xp: 150,
        studyMinutes: 45,
        completedMilestones: [],
        solvedProblemsCount: 2,
        quizScores: {},
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      };
      await setDoc(userDocRef, initialProfile);
      setProfile(initialProfile);

      // 2. Fetch all user's deadlines and delete them
      const dlQuery = query(collection(db, "deadlines"), where("userId", "==", user.uid));
      const dlSnap = await getDocs(dlQuery);
      for (const d of dlSnap.docs) {
        await deleteDoc(doc(db, "deadlines", d.id));
      }
      // Seeding preset deadlines for this user
      const dlPresets = [
        { title: "Complete CS Recursion Exercises", subject: "Computer Science", date: "2026-06-20", completed: false },
        { title: "Math Assignment 4: Integrals", subject: "Calculus", date: "2026-06-22", completed: false },
        { title: "Physics Lab Data Plotting", subject: "Physics", date: "2026-06-18", completed: true }
      ];
      for (let i = 0; i < dlPresets.length; i++) {
        await setDoc(doc(db, "deadlines", `dl-uid-preset-${i}-${user.uid}`), {
          ...dlPresets[i],
          userId: user.uid,
          createdAt: new Date().toISOString()
        });
      }

      // 3. Delete and seed studyLogs
      const logQuery = query(collection(db, "studyLogs"), where("userId", "==", user.uid));
      const logSnap = await getDocs(logQuery);
      for (const l of logSnap.docs) {
        await deleteDoc(doc(db, "studyLogs", l.id));
      }
      const logPresets = [
        { topic: "Recursion Concepts", duration: 25, date: "2026-06-14", xpGained: 55, comments: "Understood base cases and stack depths." },
        { topic: "Riemann Integration", duration: 30, date: "2026-06-15", xpGained: 65, comments: "Calculated infinite rectangular bounds." }
      ];
      for (let i = 0; i < logPresets.length; i++) {
        await setDoc(doc(db, "studyLogs", `log-uid-preset-${i}-${user.uid}`), {
          ...logPresets[i],
          userId: user.uid,
          createdAt: new Date().toISOString()
        });
      }

      // 4. Reset ScratchNotes
      await setDoc(doc(db, "scratchNotes", user.uid), {
        userId: user.uid,
        content: "# Custom Research Draft Pads & Equations\n\nWelcome! This workspace pad is **backed by our active cloud Firestore database**.",
        updatedAt: new Date().toISOString()
      });

      // 5. Delete and seed resources
      const resQuery = query(collection(db, "resources"), where("userId", "==", user.uid));
      const resSnap = await getDocs(resQuery);
      for (const r of resSnap.docs) {
        await deleteDoc(doc(db, "resources", r.id));
      }
      const resPresets = [
        { title: "MIT OpenCourseWare: Introduction to Algorithms", url: "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/", courseSubject: "Computer Science", category: "Textbook", notes: "Top-tier reference material on recursion, asymptotic runtimes, heap structures, and graph traversals.", isFavorite: true },
        { title: "Paul's Online Math Notes: Calculus I", url: "https://tutorial.math.lamar.edu/classes/calcI/calcI.aspx", courseSubject: "Calculus", category: "Cheat Sheet", notes: "Best-in-class concise notes with solved practices on limits, continuity, derivative formulas, and integrations.", isFavorite: true }
      ];
      for (let i = 0; i < resPresets.length; i++) {
        await setDoc(doc(db, "resources", `res-uid-preset-${i}-${user.uid}`), {
          ...resPresets[i],
          userId: user.uid,
          createdAt: new Date().toISOString()
        });
      }

      showToast("🧹 Firestore Cloud Datastore has been reset to presets successfully!", "success");
    } catch (e) {
      handleFirestoreError(e, OperationType.WRITE, "reset_all");
    } finally {
      setDbResetting(false);
    }
  };

  // Pomodoro ticking interval logic
  useEffect(() => {
    if (timerIsRunning) {
      timerIntervalRef.current = setInterval(() => {
        setTimerSecondsLeft((prev) => {
          if (prev <= 1) {
            const addedMinutes = Math.floor(timerInitial / 60);
            
            handleProfileUpdate(p => {
              const newXp = p.xp + 50;
              if (currentUser?.name) {
                submitLeaderboardScore(currentUser.name, newXp, `Elite Level ${Math.floor(newXp / 100) + 1} Mind 🌟`);
              }
              return {
                ...p,
                xp: newXp,
                studyMinutes: p.studyMinutes + addedMinutes
              };
            });

            const logTopic = generatedCourse ? `Module: ${generatedCourse.title}` : `Focused study session`;
            logStudySessionToServer(logTopic, addedMinutes, 50, `Completed persistent Pomodoro stopwatch segment of ${addedMinutes}m.`);

            setTimerIsRunning(false);
            if (timerIntervalRef.current) clearInterval(timerIntervalRef.current);
            showToast("🔥 Phenomenal focus! Syncing +50 XP and study session logs with database!", "success");
            
            return timerInitial;
          }
          return prev - 1;
        });
      }, 1000);
    } else {
      if (timerIntervalRef.current) clearInterval(timerIntervalRef.current);
    }
    return () => {
      if (timerIntervalRef.current) clearInterval(timerIntervalRef.current);
    };
  }, [timerIsRunning, timerInitial, generatedCourse]);

  // Auth logins success triggers
  const handleAuthSuccess = (user: { name: string; email: string }) => {
    setIsLoggedIn(true);
    setCurrentUser(user);
    localStorage.setItem("study_path_logged_in", "true");
    localStorage.setItem("study_path_current_user", JSON.stringify(user));
  };

  const handleDemoLogin = () => {
    const guestUser = { name: "Guest Scholar", email: "scholar@studypath.edu" };
    setIsLoggedIn(true);
    setCurrentUser(guestUser);
    localStorage.setItem("study_path_logged_in", "true");
    localStorage.setItem("study_path_current_user", JSON.stringify(guestUser));
    showToast("Logged in using Guest academic profile!", "success");
  };

  const handleLogout = async () => {
    try {
      await signOut(auth);
    } catch (_) {}
    setIsLoggedIn(false);
    setCurrentUser(null);
    localStorage.removeItem("study_path_logged_in");
    localStorage.removeItem("study_path_current_user");
    showToast("Logged out successfully.", "info");
  };

  // If not logged-in, render visual landing views page
  if (!isLoggedIn) {
    return (
      <Landing 
        onLoginSuccess={handleAuthSuccess}
        onDemoLogin={handleDemoLogin}
        showToast={showToast}
      />
    );
  }

  // Logged-in dashboard & custom routes tab controller
  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 flex flex-col font-sans selection:bg-indigo-500/30 selection:text-white">
      
      {/* Toast Alert popouts */}
      {toast && (
        <div className={`fixed top-4 right-4 z-50 p-4 rounded-xl shadow-2xl transition-all duration-300 transform scale-100 border flex items-center gap-3 animate-bounce ${
          toast.type === "success" 
            ? "bg-slate-900/95 border-indigo-500 text-indigo-200" 
            : "bg-slate-900/95 border-amber-500 text-amber-200"
        }`}>
          <div className="h-2 w-2 rounded-full bg-indigo-500 animate-ping" />
          <span className="text-xs font-semibold">{toast.message}</span>
        </div>
      )}

      {/* Shared Navigation Header */}
      <header id="main-app-header" className="border-b border-slate-900 bg-slate-950/75 backdrop-blur-md sticky top-0 z-30">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-indigo-600 flex items-center justify-center shadow-lg shadow-indigo-600/25 border border-indigo-400/20">
              <GraduationCap className="text-white" size={20} />
            </div>
            <div>
              <span className="text-[9px] text-indigo-400 font-extrabold uppercase tracking-widest block leading-none">Companion Engine</span>
              <span className="text-sm font-black text-slate-100 tracking-tight block">Study Path</span>
            </div>
          </div>

          {/* Dynamic tabs controller acting as routes */}
          <nav className="hidden md:flex items-center gap-1 sm:gap-2">
            <button
              onClick={() => setActiveTab('dashboard')}
              className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-all cursor-pointer ${
                activeTab === 'dashboard' 
                  ? "bg-indigo-600 text-white shadow shadow-indigo-600/10" 
                  : "text-slate-400 hover:text-slate-200 hover:bg-slate-900"
              }`}
            >
              Dashboard
            </button>
            <button
              onClick={() => setActiveTab('courses')}
              className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-all cursor-pointer ${
                activeTab === 'courses' 
                  ? "bg-indigo-600 text-white shadow shadow-indigo-600/10" 
                  : "text-slate-400 hover:text-slate-200 hover:bg-slate-900"
              }`}
            >
              Study Planner
            </button>
            <button
              onClick={() => setActiveTab('problems')}
              className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-all cursor-pointer ${
                activeTab === 'problems' 
                  ? "bg-indigo-600 text-white shadow shadow-indigo-600/10" 
                  : "text-slate-400 hover:text-slate-200 hover:bg-slate-900"
              }`}
            >
              Roadblock Solver
            </button>
            <button
              onClick={() => setActiveTab('signlang')}
              className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-all cursor-pointer ${
                activeTab === 'signlang' 
                  ? "bg-indigo-600 text-white shadow shadow-indigo-600/10" 
                  : "text-slate-400 hover:text-slate-200 hover:bg-slate-900"
              }`}
            >
              Sign Language
            </button>
            <button
              onClick={() => setActiveTab('resources')}
              className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-all cursor-pointer ${
                activeTab === 'resources' 
                  ? "bg-indigo-600 text-white shadow shadow-indigo-600/10" 
                  : "text-slate-400 hover:text-slate-200 hover:bg-slate-900"
              }`}
            >
              Resource Library
            </button>
          </nav>

          {/* User logout and profile controls */}
          <div className="flex items-center gap-3">
            <div 
              onClick={() => setActiveTab('dashboard')}
              className="relative h-9 w-9 rounded-full overflow-hidden border border-slate-850 hover:border-indigo-500 transition-colors cursor-pointer shrink-0 bg-slate-900 flex items-center justify-center group"
              title="Click to customize profile avatar"
            >
              <img 
                src={profile.avatarUrl || "https://picsum.photos/seed/defaultscholar/100/100"} 
                alt="User Profile Portrait" 
                className="w-full h-full object-cover group-hover:scale-105 transition-transform"
                referrerPolicy="no-referrer"
              />
            </div>

            <div className="hidden sm:flex flex-col text-right">
              <span className="text-xs font-bold text-slate-200 truncate max-w-[120px]">{currentUser?.name}</span>
              <span className="text-[9px] text-slate-500 font-mono font-bold uppercase">{profile.xp} XP</span>
            </div>
            
            <button
              onClick={handleLogout}
              className="p-2 bg-slate-900 hover:bg-slate-800 text-slate-400 hover:text-red-400 border border-slate-800 rounded-lg transition-colors cursor-pointer"
              title="End active session"
            >
              <LogOut size={14} />
            </button>
          </div>
        </div>
      </header>

      {/* Main Container */}
      <main className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-6 pb-24 md:pb-16">
        
        {/* Render Tab Views cleanly acting as router switch */}
        {activeTab === 'dashboard' && (
          <Dashboard
            currentUser={currentUser}
            profile={profile}
            setProfile={handleProfileUpdate}
            serverDeadlines={serverDeadlines}
            serverStudyLogs={serverStudyLogs}
            serverLeaderboard={serverLeaderboard}
            scratchNotesInput={scratchNotesInput}
            setScratchNotesInput={setScratchNotesInput}
            notesSaving={notesSaving}
            leaderboardSubmitting={leaderboardSubmitting}
            dbResetting={dbResetting}
            newDlTitle={newDlTitle}
            setNewDlTitle={setNewDlTitle}
            newDlSubject={newDlSubject}
            setNewDlSubject={setNewDlSubject}
            newDlDate={newDlDate}
            setNewDlDate={setNewDlDate}
            submitDeadlineToServer={submitDeadlineToServer}
            toggleDeadlineOnServer={toggleDeadlineOnServer}
            deleteDeadlineFromServer={deleteDeadlineFromServer}
            saveScratchNotesToServer={saveScratchNotesToServer}
            submitLeaderboardScore={submitLeaderboardScore}
            resetFullstackDatabaseInstance={resetFullstackDatabaseInstance}
            setActiveTab={setActiveTab}
            showToast={showToast}
          />
        )}

        {activeTab === 'courses' && (
          <Courses
            currentUser={currentUser}
            profile={profile}
            setProfile={handleProfileUpdate}
            targetSubject={targetSubject}
            setTargetSubject={setTargetSubject}
            targetTopic={targetTopic}
            setTargetTopic={setTargetTopic}
            targetLevel={targetLevel}
            setTargetLevel={setTargetLevel}
            generatingCourse={generatingCourse}
            setGeneratingCourse={setGeneratingCourse}
            generatedCourse={generatedCourse}
            setGeneratedCourse={setGeneratedCourse}
            COURSE_PRESETS={COURSE_PRESETS}
            timerIsRunning={timerIsRunning}
            setTimerIsRunning={setTimerIsRunning}
            timerSecondsLeft={timerSecondsLeft}
            setTimerSecondsLeft={setTimerSecondsLeft}
            timerInitial={timerInitial}
            setTimerInitial={setTimerInitial}
            courseQuizAnswers={courseQuizAnswers}
            setCourseQuizAnswers={setCourseQuizAnswers}
            courseQuizChecked={courseQuizChecked}
            setCourseQuizChecked={setCourseQuizChecked}
            courseQuizScore={courseQuizScore}
            setCourseQuizScore={setCourseQuizScore}
            showToast={showToast}
            submitLeaderboardScore={submitLeaderboardScore}
          />
        )}

        {activeTab === 'problems' && (
          <Problems
            currentUser={currentUser}
            profile={profile}
            setProfile={handleProfileUpdate}
            problemSubject={problemSubject}
            setProblemSubject={setProblemSubject}
            problemText={problemText}
            setProblemText={setProblemText}
            explainingProblem={explainingProblem}
            setExplainingProblem={setExplainingProblem}
            explainedProblem={explainedProblem}
            setExplainedProblem={setExplainedProblem}
            PROBLEM_PRESETS={PROBLEM_PRESETS}
            currentProblemStep={currentProblemStep}
            setCurrentProblemStep={setCurrentProblemStep}
            stepQuizAnswer={stepQuizAnswer}
            setStepQuizAnswer={setStepQuizAnswer}
            quizChecked={quizChecked}
            setQuizChecked={setQuizChecked}
            quizSuccess={quizSuccess}
            setQuizSuccess={setQuizSuccess}
            showToast={showToast}
            submitLeaderboardScore={submitLeaderboardScore}
          />
        )}

        {activeTab === 'signlang' && (
          <SignLanguage
            currentUser={currentUser}
            profile={profile}
            setProfile={handleProfileUpdate}
            showToast={showToast}
            submitLeaderboardScore={submitLeaderboardScore}
          />
        )}

        {activeTab === 'resources' && (
          <ResourceLibrary
            currentUser={currentUser}
            profile={profile}
            resources={serverResources}
            onAddResource={addResourceToServer}
            onToggleFavorite={toggleResourceFavoriteOnServer}
            onDeleteResource={deleteResourceFromServer}
            showToast={showToast}
            COURSE_PRESETS={COURSE_PRESETS}
          />
        )}

      </main>

      {/* Page unified Footer info */}
      <footer className="bg-slate-950/40 border-t border-slate-900/60 py-6 text-center text-slate-500 text-[10px] mt-auto font-sans pb-24 md:pb-6">
        <div className="max-w-7xl mx-auto px-4 flex flex-col sm:flex-row items-center sm:justify-between gap-3 text-slate-500">
          <div className="flex items-center gap-1.5 text-slate-400 font-extrabold font-sans uppercase">
            <Sparkles size={11} className="text-indigo-500" />
            <span>Study Path Companion</span>
          </div>
          <p>© {new Date().getFullYear()} Study Path Academic Node. Fully synced with Express DB.</p>
        </div>
      </footer>

      {/* Floating Bottom Navigation for Mobile Devices */}
      <nav className="fixed bottom-0 left-0 right-0 z-40 bg-slate-950/95 backdrop-blur-md border-t border-slate-900 md:hidden flex justify-around items-center h-16 pb-safe px-2">
        <button
          onClick={() => setActiveTab('dashboard')}
          className={`flex flex-col items-center justify-center flex-1 h-full py-1 text-center transition-colors cursor-pointer ${
            activeTab === 'dashboard' ? "text-indigo-400" : "text-slate-400 hover:text-slate-200"
          }`}
        >
          <Home size={18} />
          <span className="text-[9px] font-medium mt-1">Dashboard</span>
        </button>
        <button
          onClick={() => setActiveTab('courses')}
          className={`flex flex-col items-center justify-center flex-1 h-full py-1 text-center transition-colors cursor-pointer ${
            activeTab === 'courses' ? "text-indigo-400" : "text-slate-400 hover:text-slate-200"
          }`}
        >
          <BookOpen size={18} />
          <span className="text-[9px] font-medium mt-1">Planner</span>
        </button>
        <button
          onClick={() => setActiveTab('problems')}
          className={`flex flex-col items-center justify-center flex-1 h-full py-1 text-center transition-colors cursor-pointer ${
            activeTab === 'problems' ? "text-indigo-400" : "text-slate-400 hover:text-slate-200"
          }`}
        >
          <HelpCircle size={18} />
          <span className="text-[9px] font-medium mt-1">Solver</span>
        </button>
        <button
          onClick={() => setActiveTab('signlang')}
          className={`flex flex-col items-center justify-center flex-1 h-full py-1 text-center transition-colors cursor-pointer ${
            activeTab === 'signlang' ? "text-indigo-400" : "text-slate-400 hover:text-slate-200"
          }`}
        >
          <Sparkles size={18} />
          <span className="text-[9px] font-medium mt-1">Sign Lang</span>
        </button>
        <button
          onClick={() => setActiveTab('resources')}
          className={`flex flex-col items-center justify-center flex-1 h-full py-1 text-center transition-colors cursor-pointer ${
            activeTab === 'resources' ? "text-indigo-400" : "text-slate-400 hover:text-slate-200"
          }`}
        >
          <Bookmark size={18} />
          <span className="text-[9px] font-medium mt-1">Resources</span>
        </button>
      </nav>

    </div>
  );
}
